spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:adm_videos_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE # É possível persistir em um arquivo alterando "mem:adm_videos_test" para "file:./.h2/dev"
  h2:
    console:
      enabled: true
      path: /h2

    #PROFILE DE TESTE
    #O profile de teste é ativado quando o profile "test" é ativado.
    #O profile de teste substitui o profile de desenvolvimento.
    #PRA ISSO PRA TEST USAMOS O BANCO DE DADOS H2
    #O H2 é um banco de dados em memória que pode ser usado para testes.
