package com.esdras.catalogo.videos.application;

//PRA CADA TIPO DE CASO DE USO, TEMOS UMA CLASSE ABSTRATA
//QUE DEFINE O MOLDE DO NOSSOS CASOS DE USO
public abstract class UseCase<IN,OUT> {

    //E AQUI ESTAMOS DEFININDO O METODO EXECUTE
    //QUE VAI RECEBER UM IN E RETORNAR UM OUT
    //E O METODO EXECUTE VAI SER IMPLEMENTADO PELAS CLASSES CONCRETAS
    //O CASO DE USO PODE RECEBER UM COMANDO OU NÃO, DEPENDENDO DO CASO DE USO
    //A MAIOR PARTE DOS CASOS DE USO VÃO SEGUIR ESSA ABSTRAÇÃO
    //MAS TEMOS CASOS IGUAL NO TCC QUE EU VC FEZ EU
    //QUE NÃO VAI TER ENTRADA E NEM SAIDA
    //MAS A MAIOR PARTE DOS CASOS DE USO VÃO SEGUIR ESSA ABSTRAÇÃO
    //POR CONVENÇÃO ATE MESMO DO MARTIN FOWLER E DO ERIC EVANS
    //O CASO DE USO TEM UM UNICO METODO PUBLICO QUE É O E EXECUTE
    //ENTÃO VAMOS SEGUIR ESSSA NOMECLATURA
    public abstract OUT execute(IN anIn);

}
